### ISSUE TITLE
编译出的东西能兼容Actinium吗？

### ISSUE THREAD

**Issue by daiaji** [xiaokangwang/AndroidLibV2ray#18]
虽然Actinium凉了很久
还有就是有具体编译教程吗
我编译总报错 怀疑是环境变量不对

**Comment by daiaji** [comment]
make下去
`protoc --go_out=. LibV2Ray.proto LibV2RayConfigure.proto
Done
make[1]: Leaving directory '/home/daiaji/AndroidLibV2ray/configure'`
好像没出东西

**Comment by xiaokangwang** [comment]
兼容的，请参考ci的方式编译

**Comment by yoshikotama** [comment]
我使用项目提供的makefile文件中的部分内容最终编译出了aar文件，直接使用此文件替换Actinium的旧版本文件并Build后，启动代理时FC并反复输出如下内容：
>11-19 21:25:30.241 10720-0/? E/Go: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f69263064]
11-19 21:25:30.241 10720-10747/? E/GoLog: panic: runtime error: invalid memory address or nil pointer dereference
11-19 21:25:30.241 10720-0/? E/Go: goroutine 24 [running]:
11-19 21:25:30.241 10720-0/? E/Go: github.com/xiaokangwang/AndroidLibV2ray.(*V2RayPoint).pointloop(0x4420136090)
11-19 21:25:30.242 10720-0/? E/Go: 	/home/zyh/gopath/src/github.com/xiaokangwang/AndroidLibV2ray/interact.go:81 +0xaf4
11-19 21:25:30.242 10720-0/? E/Go: created by github.com/xiaokangwang/AndroidLibV2ray.(*V2RayPoint).RunLoop
11-19 21:25:30.242 10720-0/? E/Go: 	/home/zyh/gopath/src/github.com/xiaokangwang/AndroidLibV2ray/interact.go:220 +0x70
11-19 21:25:31.394 10767-10774/? E/art: Failed sending reply to debugger: Broken pipe

checkout 2.47、2.49、2.50均出现了此错误。<del>其余部分版本无法编译。</del>
编译过程中是否有其他应该注意的事项？

**Comment by daiaji** [comment]
@yoshikotama ?
我还是先不编译了吧……
怕不是API不兼容

**Comment by xiaokangwang** [comment]
你尝试一下使用一个在V2RayGo下能用的配置文件？

**Comment by yoshikotama** [comment]
@daiaji 恐怕不是不兼容。v2raygo的v2raylib是25+2.47的组合，并不会报错。出错有可能是我的问题。
@xiaokangwang 稍后我试一下

**Comment by yoshikotama** [comment]
@daiaji 还有，你应该把`$GOPATH/bin`加入到PATH中，否则protoc是没法用的，第一步`make pb`都走不通。

**Comment by daiaji** [comment]
@yoshikotama 我看看

**Comment by yoshikotama** [comment]
@xiaokangwang @daiaji `6f885e0 v2.49`可以正常运行。确实是配置文件的问题。actinium最后一版使用了旧版的json模板，所以在直接替换aar之后会崩溃。使用了README中提到的配置文件就能正常运行。

**Comment by yoshikotama** [comment]
<del>geosite、geoip、chinaip、chinasites均无法使用。是否是core2.46与2.47的问题？</del>
漏掉了`make asset`

**Comment by chenyue404** [comment]
编译出来aar之后能发出来吗？更喜欢用Actinium，然而不会编译AndroidLibV2ray……

**Comment by xiaokangwang** [comment]
近期准备实现定期发布aar

**Comment by daiaji** [comment]
@yoshikotama 兄弟你Fork一下Actinium吧
然后改一下那个模板
编译的话
应该是一发make就能出东西吧

**Comment by xiaokangwang** [comment]
你们觉得有必要实现像V2Ray一样自动发布程序的功能么？

**Comment by daiaji** [comment]
@xiaokangwang 一劳永逸挺好的 老实说 我这破网编译真是够呛
挂了SSR更慢 V2ray路由器跑太吃力了

**Comment by xiaokangwang** [comment]
https://github.com/xiaokangwang/AndroidLibV2ray/releases

**Comment by xiaokangwang** [comment]
可以测试一下这里的release

**Comment by chenyue404** [comment]
编译正常，启动vpn的时候报如下错误：
Process: com.v2ray.actinium, PID: 21357
                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
                                                                     Caused by: android.os.DeadObjectException
                                                                        at android.os.BinderProxy.transactNative(Native Method)
                                                                        at android.os.BinderProxy.transact(Binder.java:628)
                                                                        at com.v2ray.actinium.aidl.IV2RayService$Stub$Proxy.unregisterCallback(IV2RayService.java:158)
                                                                        at com.v2ray.actinium.ui.MainActivity$conn$1.onServiceDisconnected(MainActivity.kt:67)
                                                                        at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1532)
                                                                        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1546)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by chenyue404** [comment]
编译通过，开启vpn的时候，报如下错误：
Process: com.v2ray.actinium, PID: 15054
                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                                        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103) 
                                                                     Caused by: android.os.DeadObjectException
                                                                        at android.os.BinderProxy.transactNative(Native Method)
                                                                        at android.os.BinderProxy.transact(Binder.java:651)
                                                                        at com.v2ray.actinium.aidl.IV2RayService$Stub$Proxy.unregisterCallback(IV2RayService.java:158)
                                                                        at com.v2ray.actinium.ui.MainActivity$conn$1.onServiceDisconnected(MainActivity.kt:67)
                                                                        at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1515)
                                                                        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1529)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6321)
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                                        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)

**Comment by xiaokangwang** [comment]
应该是因为进程崩溃了，你需要根据新的V2Ray的配置文件的要求写一个配置文件之后导入

**Comment by chenyue404** [comment]
我是导入的时候，选择转换成兼容的。奇怪的是，三星s6就可以，一加3T就不行……

**Comment by chenyue404** [comment]
直接用https://github.com/xiaokangwang/AndroidLibV2ray/blob/master/conf/config_mobile.json也报同样的错误

**Comment by chenyue404** [comment]
嗯，是配置文件的问题。但是又发现一个问题，只要加上chinaip直连，就会崩……
chinasites加上没问题，但是好像没生效。

**Comment by yoshikotama** [comment]
@chenyue404 检查一下`asset`文件夹下的`geoip.dat`和`geosite.dat`。这两个文件不完整可能会引发崩溃。我之前那次漏掉`make asset`时，没有那两个文件就会导致崩溃。
@daiaji 对项目不太熟悉，暂时还不敢fork。你肯定不希望一个一问三不知的甩手掌柜接受这个项目吧（笑）。另外，直接make会做一些重复的工作，我是手动一步步来的。

**Comment by chenyue404** [comment]
@yoshikotama 谢谢提醒。刚刚按照https://toutyrater.github.io/app/routing-for-android.html 搞定了chinasites, chinaip还是会崩，在`asset`里面加入`geoip.dat`和`geosite.dat`之后就好了。
但是发现加了chinasites和chinaip之后，百度搜索还是会走代理，不过应该不是bug，只是规则问题，不知道你有没有好的办法解决。

**Comment by daiaji** [comment]
@xiaokangwang @yoshikotama @chenyue404 嗯编译apk的时候
`> File google-services.json is missing. The Google Services Plugin cannot function without it. `
为什么我要申请自己的gms啦！我只是想更新个lib而已啊！
个小破代理为什么要gms啊！
又不用接收后台推送的！
我等你们改好吧！

**Comment by chenyue404** [comment]
@daiaji 把firebase相关代码注释掉就行了

**Comment by yoshikotama** [comment]
@chenyue404 <del>不知道，很迷。chinasites/geoip:cn对熊度没起作用。</del>
`inbound`下加入`"domainOverride": ["http", "tls"],`，还是不完美，有些域名即使被嗅探出来仍然会使用代理。比如，淘宝还是会进全球站，但是显示`taking detour [direct] for [tcp:www.taobao.com:443]`

**Comment by yoshikotama** [comment]
然后是`taking detour [direct] for [tcp:m.intl.taobao.com:443]`。怀疑8.8.8.8解析出阿里的是淘宝国际版的主机。有可能是因为chinasites的DNS请求也被转发了，导致解析返回了用于海外的IP地址。。

**Comment by daiaji** [comment]
@yoshikotama ~~能使的json模板给我一个
我不太想翻手册了~~
放上去终于不报错了
那么着手修复这几个可能的BUG吧
Kotlin？尝试一下？
```
    sevenzip {
        artifact = 'com.tencent.mm:SevenZip:1.2.3'
        //path = "/usr/local/bin/7za"
    }
```
不是很理解
为啥要加进来呢？
KPI要求吗？业界真是可怕啊
